detailsv1:
  image: istio/examples-bookinfo-details-v1:1.10.1
  pullPolicy: IfNotPresent
ratingsv2:
  image: istio/examples-bookinfo-ratings-v1:1.10.1
  pullPolicy: IfNotPresent
reviewsv1:
  image: istio/examples-bookinfo-reviews-v1:1.10.1
  pullPolicy: IfNotPresent
reviewsv2:
  image: istio/examples-bookinfo-reviews-v2:1.10.1
  pullPolicy: IfNotPresent
reviewsv3:
  image: istio/examples-bookinfo-reviews-v3:1.10.1
  pullPolicy: IfNotPresent
productpagev1:
  image: istio/examples-bookinfo-productpage-v1:1.10.1
  pullPolicy: IfNotPresent
