apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: icam-demo
    appname: bookinfo-flat
  name: bookinfo-subscription-bookinfo
  namespace: bookinfo-project
spec:
  channel: bookinfo-entitlement/bookinfo-channel
  name: bookinfo
  packageFilter:
    version: 1.1.0
  placement:
    placementRef:
      name: demo-placementrule
      kind: PlacementRule
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: bookinfo
  packageOverrides:
  - packageName: bookinfo
    packageOverrides:
    - path: spec.releaseName
      value: bookinfo-demo
    - path: spec.values
      value: |
        ingress:
          host: bookinfo.9.30.119.120.nip.io
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: icam-demo
    appname: bookinfo-flat
  name: bookinfo-subscription-details
  namespace: bookinfo-project
spec:
  channel: bookinfo-entitlement/bookinfo-channel
  name: details
  packageFilter:
    version: 1.1.0
  placement:
    placementRef:
      name: demo-placementrule
      kind: PlacementRule
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: bookinfo
  packageOverrides:
  - packageName: details
    packageOverrides:
    - path: spec.releaseName
      value: bookinfo-demo-details
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: icam-demo
    appname: bookinfo-flat
  name: bookinfo-subscription-productpage
  namespace: bookinfo-project
spec:
  channel: bookinfo-entitlement/bookinfo-channel
  name: productpage
  packageFilter:
    version: 1.1.0
  placement:
    placementRef:
      name: demo-placementrule
      kind: PlacementRule
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: bookinfo
  packageOverrides:
  - packageName: productpage
    packageOverrides:
    - path: spec.releaseName
      value: bookinfo-demo-productpage
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: icam-demo
    appname: bookinfo-flat
  name: bookinfo-subscription-ratings
  namespace: bookinfo-project
spec:
  channel: bookinfo-entitlement/bookinfo-channel
  name: ratings
  packageFilter:
    version: 1.1.0
  placement:
    placementRef:
      name: demo-placementrule
      kind: PlacementRule
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: bookinfo
  packageOverrides:
  - packageName: ratings
    packageOverrides:
    - path: spec.releaseName
      value: bookinfo-demo-ratings
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: icam-demo
    appname: bookinfo-flat
  name: bookinfo-subscription-reviews
  namespace: bookinfo-project
spec:
  channel: bookinfo-entitlement/bookinfo-channel
  name: reviews
  packageFilter:
    version: 1.1.0
  placement:
    placementRef:
      name: demo-placementrule
      kind: PlacementRule
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: bookinfo
  packageOverrides:
  - packageName: reviews
    packageOverrides:
    - path: spec.releaseName
      value: bookinfo-demo-reviews
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: icam-demo
    appname: bookinfo-flat
  name: bookinfo-subscription-mysqldb
  namespace: bookinfo-project
spec:
  channel: bookinfo-entitlement/bookinfo-channel
  name: mysqldb
  packageFilter:
    version: 1.1.0
  placement:
    placementRef:
      name: demo-placementrule
      kind: PlacementRule
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: bookinfo
  packageOverrides:
  - packageName: mysqldb
    packageOverrides:
    - path: spec.releaseName
      value: bookinfo-demo-mysqldb
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: bookinfo-app-flat
  namespace: bookinfo-project
spec:
  selector:
    matchExpressions:
    - key: purpose
      operator: In
      values:
      - icam-demo
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
