---
# Source: bookinfo/charts/mysqldb/templates/secret.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: bookinfo-mysqldb-secret-deployable
  namespace: bookinfo-entitlement
  labels:
    appname: bookinfo-demo
    release: bookinfo-demo
spec:
  template:
    apiVersion: v1
    kind: Secret
    metadata:
      name: mysql-credentials
      namespace: bookinfo
    type: Opaque
    data:
      rootpasswd: cGFzc3dvcmQ=
---
# Source: bookinfo/charts/details/templates/service-account.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: bookinfo-reviews-sa-deployable
  namespace: bookinfo-entitlement
  labels:
    appname: bookinfo-demo
    release: bookinfo-demo
spec:
  template:
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: bookinfo-reviews
---
# Source: bookinfo/charts/reviews/templates/clusterrole.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: bookinfo-reviews-rbac-deployable
  namespace: bookinfo-entitlement
  labels:
    appname: bookinfo-demo
    release: bookinfo-demo
spec:
  template:
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: reviews-lwdc-query
    rules:
    - apiGroups:
      - ""
      - apps
      resources:
      - clusters
      - nodes
      - services
      - configmaps
      - pods
      - endpoints
      - deployments
      verbs:
      - list
      - get
    - apiGroups:
      - extensions
      attributeRestrictions: null
      resourceNames:
      - ibm-anyuid-psp
      resources:
      - podsecuritypolicies
      verbs:
      - use
    - apiGroups:
      - security.openshift.io 
      resources:
      - securitycontextconstraints 
      verbs:
      - use
      resourceNames:
      - anyuid
---
# Source: bookinfo/charts/reviews/templates/rolebinding.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: bookinfo-reviews-crb-deployable
  namespace: bookinfo-entitlement
  labels:
    appname: bookinfo-demo
    release: bookinfo-demo
spec:
  template:
    kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: reviews-lwdc-rolebinding
      namespace: bookinfo
    subjects:
    - kind: User
      name: system:serviceaccount:bookinfo:bookinfo-reviews
      apiGroup: rbac.authorization.k8s.io
    roleRef:
      kind: ClusterRole
      name: reviews-lwdc-query
      apiGroup: rbac.authorization.k8s.io
