apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-lwdc-query
rules:
- apiGroups:
  - ""
  resources:
  - clusters
  - nodes
  - services
  - configmaps
  - pods
  verbs:
  - list
  - get
- apiGroups:
  - extensions
  attributeRestrictions: null
  resourceNames:
  - ibm-anyuid-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
