apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ImagePolicy
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    # app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    # "helm.sh/hook": pre-install
    # "helm.sh/hook-weight": "-5"
    # "helm.sh/hook-delete-policy": hook-succeeded
  name: {{ include "productpage.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  repositories:
  - name: "{{ .Values.image.repository }}:*"
    policy:
      va:
        enabled: false

